/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.ConexaoBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;
import model.dados.ModeloTabela;

/**
 *
 * @author Kira
 */
public class TelaListar extends javax.swing.JFrame {
    ConexaoBD conecta = new ConexaoBD();
    private Timer timer;

    /**
     * Creates new form TelaListar
     */
    public TelaListar(){
        initComponents();
        preencherTabela("select *from clientes order by nome");
    }
     public class cron implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            GregorianCalendar tempo = new GregorianCalendar();
            int hora,minutos,segundos;
            hora=tempo.get(Calendar.HOUR);
            minutos=tempo.get(Calendar.MINUTE);
            segundos=tempo.get(Calendar.SECOND);
            
            lbHoras.setText(String.valueOf(hora));
            lbMinutos.setText(String.valueOf(minutos));
            lbSegundos.setText(String.valueOf(segundos));
        }

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtListarCliente = new javax.swing.JTable();
        btSairListarCliente = new javax.swing.JButton();
        btVoltarListarClientes1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbSegundos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbMinutos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbHoras = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jtListarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtListarCliente);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 520, 200);

        btSairListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Sair.png"))); // NOI18N
        btSairListarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSairListarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSairListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairListarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btSairListarCliente);
        btSairListarCliente.setBounds(550, 280, 60, 60);

        btVoltarListarClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/back.png"))); // NOI18N
        btVoltarListarClientes1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btVoltarListarClientes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarListarClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarListarClientes1ActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltarListarClientes1);
        btVoltarListarClientes1.setBounds(20, 280, 60, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        lbSegundos.setText("00");
        jPanel2.add(lbSegundos);
        lbSegundos.setBounds(70, 0, 30, 30);

        jLabel5.setText(":");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 0, 10, 30);

        lbMinutos.setText("00");
        jPanel2.add(lbMinutos);
        lbMinutos.setBounds(40, 0, 40, 30);

        jLabel7.setText(":");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 0, 10, 30);

        lbHoras.setText("00");
        jPanel2.add(lbHoras);
        lbHoras.setBounds(10, 0, 30, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(260, 310, 90, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Logo Javaadul - Cópia.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jPanel1.add(jButton1);
        jButton1.setBounds(540, 10, 80, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/papel-de-parede-3d-7.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 360);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 630, 360);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTAR CLIENTES");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 10, 120, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/thumb2-abstract-background-black-wave-stock-wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 670, 420);

        setSize(new java.awt.Dimension(685, 453));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarListarClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarListarClientes1ActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltarListarClientes1ActionPerformed

    private void btSairListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairListarClienteActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairListarClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer = new Timer(1000,new TelaListar.cron());
        timer.start();
    }//GEN-LAST:event_formWindowOpened
    
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD-CLIENTE", "Nome","CPF","Endereco","Telefone","Email"};
        conecta.conexao();
        conecta.executaSql(sql);
        try{
            conecta.rs.first();
            do{
                //ADICIONA OS DADOS DO ARRAYLIST NA LINHA DA TABELA
                dados.add(new Object[]{conecta.rs.getInt("cod_cliente"),conecta.rs.getString("nome"),conecta.rs.getString("cpf"),conecta.rs.getString("endereco"),conecta.rs.getString("telefone"),conecta.rs.getString("email")});
                
            }while(conecta.rs.next()); //ENQUANTO HOUVER DADO ELE PERCORRERÁ
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, "ERRO AO PREENCHER O ARRAYLIST!!!\n" + e.getMessage());
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas); //INSTANCIA O MODELO TABELA
        jtListarCliente.setModel(modelo);
        jtListarCliente.getColumnModel().getColumn(0).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarCliente.getColumnModel().getColumn(0).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarCliente.getColumnModel().getColumn(1).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarCliente.getColumnModel().getColumn(1).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarCliente.getColumnModel().getColumn(2).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarCliente.getColumnModel().getColumn(2).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarCliente.getColumnModel().getColumn(3).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarCliente.getColumnModel().getColumn(3).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarCliente.getColumnModel().getColumn(4).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarCliente.getColumnModel().getColumn(4).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarCliente.getColumnModel().getColumn(0).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarCliente.getTableHeader().setReorderingAllowed(false);//NÃO DEIXA REORDENAR O CABEÇALHO
        jtListarCliente.setAutoResizeMode(jtListarCliente.AUTO_RESIZE_OFF);
        jtListarCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//SÓ PERMITI SELECIONAR UM DADO POR VEZ
        conecta.desconectar();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaListar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSairListarCliente;
    private javax.swing.JButton btVoltarListarClientes1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtListarCliente;
    private javax.swing.JLabel lbHoras;
    private javax.swing.JLabel lbMinutos;
    private javax.swing.JLabel lbSegundos;
    // End of variables declaration//GEN-END:variables
}
