/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.ConexaoBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author Kira
 */
public class TelaPrincipal extends javax.swing.JFrame {

   ConexaoBD conecta = new ConexaoBD();
    private Timer timer;
   
    public TelaPrincipal() {
        initComponents();
        
        conecta.conexao();
    }
    public class cron implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            GregorianCalendar tempo = new GregorianCalendar();
            int hora,minutos,segundos;
            hora=tempo.get(Calendar.HOUR);
            minutos=tempo.get(Calendar.MINUTE);
            segundos=tempo.get(Calendar.SECOND);
            
            lbHoras.setText(String.valueOf(hora));
            lbMinutos.setText(String.valueOf(minutos));
            lbSegundos.setText(String.valueOf(segundos));
        }

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        btVoltar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbSegundos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbMinutos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbHoras = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastrar = new javax.swing.JMenu();
        miCadastrarCliente = new javax.swing.JMenuItem();
        miCadastrarServico = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miRemoverCliente = new javax.swing.JMenuItem();
        miRemoverServico = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAtualizarCliente = new javax.swing.JMenuItem();
        miAtualizarServico = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miBuscarCliente = new javax.swing.JMenuItem();
        miBuscarServico = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        miListarCliente = new javax.swing.JMenuItem();
        miListarServico = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        panel1.setLayout(null);

        btVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btVoltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/back.png"))); // NOI18N
        btVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        panel1.add(btVoltar);
        btVoltar.setBounds(20, 290, 60, 60);

        btFechar.setBackground(new java.awt.Color(255, 255, 255));
        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Sair.png"))); // NOI18N
        btFechar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        panel1.add(btFechar);
        btFechar.setBounds(580, 290, 60, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Logo Javaadul.png"))); // NOI18N
        panel1.add(jLabel2);
        jLabel2.setBounds(200, 10, 270, 360);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        lbSegundos.setText("00");
        jPanel1.add(lbSegundos);
        lbSegundos.setBounds(70, 0, 30, 30);

        jLabel5.setText(":");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 0, 10, 30);

        lbMinutos.setText("00");
        jPanel1.add(lbMinutos);
        lbMinutos.setBounds(40, 0, 40, 30);

        jLabel7.setText(":");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 0, 10, 30);

        lbHoras.setText("00");
        jPanel1.add(lbHoras);
        lbHoras.setBounds(10, 0, 30, 30);

        panel1.add(jPanel1);
        jPanel1.setBounds(540, 20, 100, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Branco5.png"))); // NOI18N
        panel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 660, 370);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 690, 390);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuBar1FocusGained(evt);
            }
        });

        cadastrar.setText("Cadastrar");

        miCadastrarCliente.setBackground(new java.awt.Color(255, 255, 255));
        miCadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        miCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/contatos.png"))); // NOI18N
        miCadastrarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarClienteActionPerformed(evt);
            }
        });
        cadastrar.add(miCadastrarCliente);

        miCadastrarServico.setBackground(new java.awt.Color(255, 255, 255));
        miCadastrarServico.setForeground(new java.awt.Color(255, 255, 255));
        miCadastrarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Servico.png"))); // NOI18N
        miCadastrarServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miCadastrarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarServicoActionPerformed(evt);
            }
        });
        cadastrar.add(miCadastrarServico);

        jMenuBar1.add(cadastrar);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Remover");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        miRemoverCliente.setBackground(new java.awt.Color(255, 255, 255));
        miRemoverCliente.setForeground(new java.awt.Color(255, 255, 255));
        miRemoverCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/user_eliminate_12817.png"))); // NOI18N
        miRemoverCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miRemoverCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoverClienteActionPerformed(evt);
            }
        });
        jMenu2.add(miRemoverCliente);

        miRemoverServico.setBackground(new java.awt.Color(255, 255, 255));
        miRemoverServico.setForeground(new java.awt.Color(255, 255, 255));
        miRemoverServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/RemoverServico.png"))); // NOI18N
        miRemoverServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miRemoverServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miRemoverServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoverServicoActionPerformed(evt);
            }
        });
        jMenu2.add(miRemoverServico);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Atualizar");

        miAtualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/users_back.png"))); // NOI18N
        miAtualizarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miAtualizarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAtualizarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(miAtualizarCliente);

        miAtualizarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/atualizar.png"))); // NOI18N
        miAtualizarServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miAtualizarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miAtualizarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAtualizarServicoActionPerformed(evt);
            }
        });
        jMenu3.add(miAtualizarServico);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Buscar");

        miBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/images.jpg"))); // NOI18N
        miBuscarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miBuscarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarClienteActionPerformed(evt);
            }
        });
        jMenu4.add(miBuscarCliente);

        miBuscarServico.setBackground(new java.awt.Color(255, 255, 255));
        miBuscarServico.setForeground(new java.awt.Color(255, 255, 255));
        miBuscarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/buscar.jpg"))); // NOI18N
        miBuscarServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miBuscarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miBuscarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarServicoActionPerformed(evt);
            }
        });
        jMenu4.add(miBuscarServico);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Listar");

        miListarCliente.setBackground(new java.awt.Color(255, 255, 255));
        miListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/SolicitudU.png"))); // NOI18N
        miListarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miListarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarClienteActionPerformed(evt);
            }
        });
        jMenu5.add(miListarCliente);

        miListarServico.setBackground(new java.awt.Color(255, 255, 255));
        miListarServico.setForeground(new java.awt.Color(255, 255, 255));
        miListarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/list_icon.jpg"))); // NOI18N
        miListarServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miListarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListarServicoActionPerformed(evt);
            }
        });
        jMenu5.add(miListarServico);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Anexos");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Calendar ICON.png"))); // NOI18N
        jMenuItem2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(665, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarClienteActionPerformed
    	TelaMapa telaMapa = new TelaMapa();
		telaMapa.setVisible(true);
        dispose();
    }//GEN-LAST:event_miCadastrarClienteActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
       TelaLogin tela = new TelaLogin(); //CHAMA A TELA LOGIN
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        conecta.desconectar(); //FECHA O BANCO DE DADOS
        System.exit(0); // FECHA A TELA
       
    }//GEN-LAST:event_btFecharActionPerformed

    private void miCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarServicoActionPerformed
       CadastroServico form = new CadastroServico();
       form.setVisible(true);
       dispose();
    }//GEN-LAST:event_miCadastrarServicoActionPerformed

    private void miBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarClienteActionPerformed
        TelaBuscarCliente tela = new TelaBuscarCliente();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miBuscarClienteActionPerformed

    private void miRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoverClienteActionPerformed
        TelaExcluirCliente tela = new TelaExcluirCliente();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miRemoverClienteActionPerformed

    private void miAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAtualizarClienteActionPerformed
        TelaAtualizar tela = new TelaAtualizar();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miAtualizarClienteActionPerformed

    private void miListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarClienteActionPerformed
        TelaAutenticacaoListar tela = new TelaAutenticacaoListar();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miListarClienteActionPerformed

    private void miListarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListarServicoActionPerformed
        TelaAutenticacaoLista tela = new TelaAutenticacaoLista();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miListarServicoActionPerformed

    private void miAtualizarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAtualizarServicoActionPerformed
        TelaAtualizarServico tela = new TelaAtualizarServico();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miAtualizarServicoActionPerformed

    private void miRemoverServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoverServicoActionPerformed
        TelaExcluirServico tela = new TelaExcluirServico();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miRemoverServicoActionPerformed

    private void miBuscarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarServicoActionPerformed
        TelaBuscarServico tela = new TelaBuscarServico();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_miBuscarServicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer = new Timer(1000,new cron());
        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jMenuBar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuBar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1FocusGained

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaCalendar tela = new TelaCalendar();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JMenu cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbHoras;
    private javax.swing.JLabel lbMinutos;
    private javax.swing.JLabel lbSegundos;
    private javax.swing.JMenuItem miAtualizarCliente;
    private javax.swing.JMenuItem miAtualizarServico;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JMenuItem miBuscarServico;
    private javax.swing.JMenuItem miCadastrarCliente;
    private javax.swing.JMenuItem miCadastrarServico;
    private javax.swing.JMenuItem miListarCliente;
    private javax.swing.JMenuItem miListarServico;
    private javax.swing.JMenuItem miRemoverCliente;
    private javax.swing.JMenuItem miRemoverServico;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables



}
