/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexao.ConexaoBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;
import model.dados.ModeloTabela;

/**
 *
 * @author Kira
 */
public class TelaListarServico extends javax.swing.JFrame {
    ConexaoBD conecta = new ConexaoBD();
    private Timer timer;
    /**
     * Creates new form TelaListarServico
     */
    public TelaListarServico() {
        initComponents();
        preencherTabela("select *from servicos order by nome");
    }
     public class cron implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            GregorianCalendar tempo = new GregorianCalendar();
            int hora,minutos,segundos;
            hora=tempo.get(Calendar.HOUR);
            minutos=tempo.get(Calendar.MINUTE);
            segundos=tempo.get(Calendar.SECOND);
            
            lbHoras.setText(String.valueOf(hora));
            lbMinutos.setText(String.valueOf(minutos));
            lbSegundos.setText(String.valueOf(segundos));
        }

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btVoltarListarServico = new javax.swing.JButton();
        btSairListarServico = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtListarServico = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbSegundos = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbMinutos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbHoras = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        btVoltarListarServico.setBackground(new java.awt.Color(255, 255, 255));
        btVoltarListarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/back.png"))); // NOI18N
        btVoltarListarServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btVoltarListarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarListarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarListarServicoActionPerformed(evt);
            }
        });
        jPanel1.add(btVoltarListarServico);
        btVoltarListarServico.setBounds(20, 230, 60, 60);

        btSairListarServico.setBackground(new java.awt.Color(255, 255, 255));
        btSairListarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Sair.png"))); // NOI18N
        btSairListarServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSairListarServico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSairListarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairListarServicoActionPerformed(evt);
            }
        });
        jPanel1.add(btSairListarServico);
        btSairListarServico.setBounds(530, 230, 60, 60);

        jtListarServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtListarServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtListarServico.setGridColor(new java.awt.Color(0, 0, 0));
        jtListarServico.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jtListarServico.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtListarServico);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 500, 180);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        lbSegundos.setText("00");
        jPanel2.add(lbSegundos);
        lbSegundos.setBounds(70, 0, 30, 30);

        jLabel5.setText(":");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 0, 10, 30);

        lbMinutos.setText("00");
        jPanel2.add(lbMinutos);
        lbMinutos.setBounds(40, 0, 40, 30);

        jLabel7.setText(":");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 0, 10, 30);

        lbHoras.setText("00");
        jPanel2.add(lbHoras);
        lbHoras.setBounds(10, 0, 30, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(250, 260, 90, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Logo Javaadul - Cópia.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton1);
        jButton1.setBounds(520, 10, 80, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/thumb2-abstract-background-black-wave-stock-wallpaper.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 610, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 610, 310);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTAR SERVIÇOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 120, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/papel-de-parede-3d-7.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 650, 380);

        setSize(new java.awt.Dimension(668, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarListarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarListarServicoActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btVoltarListarServicoActionPerformed

    private void btSairListarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairListarServicoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairListarServicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        timer = new Timer(1000,new TelaListarServico.cron());
        timer.start();
    }//GEN-LAST:event_formWindowOpened
    
    public void preencherTabela(String sql){
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"COD_SERVIÇO","ID","Nome","Solicitador","Endereco","Telefone","Valor","Data","Horario"};
        conecta.conexao();
        conecta.executaSql(sql);
        try{
            conecta.rs.first();
            do{
                //ADICIONA OS DADOS DO ARRAYLIST NA LINHA DA TABELA
                dados.add(new Object[]{conecta.rs.getInt("cod_servico"),conecta.rs.getString("id"),conecta.rs.getString("nome"),conecta.rs.getString("solicitador"),conecta.rs.getString("endereco"),conecta.rs.getString("telefone"),conecta.rs.getString("valor"),conecta.rs.getString("data"),conecta.rs.getString("horario")});
                
            }while(conecta.rs.next()); //ENQUANTO HOUVER DADO ELE PERCORRERÁ
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, "ERRO AO PREENCHER O ARRAYLIST!!!\n");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas); //INSTANCIA O MODELO TABELA
        jtListarServico.setModel(modelo);
        jtListarServico.getColumnModel().getColumn(0).setPreferredWidth(70);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(0).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarServico.getColumnModel().getColumn(1).setPreferredWidth(70);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(1).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarServico.getColumnModel().getColumn(2).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(2).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarServico.getColumnModel().getColumn(3).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(3).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarServico.getColumnModel().getColumn(4).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(4).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarServico.getColumnModel().getColumn(5).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(5).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarServico.getColumnModel().getColumn(6).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(6).setResizable(false);//IMPEDE QUE REDIMENSIONAR
        jtListarServico.getColumnModel().getColumn(7).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarServico.getColumnModel().getColumn(7).setResizable(false);//IMPEDE QUE REDIMENSIONAR       
        jtListarServico.getColumnModel().getColumn(0).setPreferredWidth(100);//TABELA TAMANHO 10
        jtListarServico.getTableHeader().setReorderingAllowed(false);//NÃO DEIXA REORDENAR O CABEÇALHO
        jtListarServico.setAutoResizeMode(jtListarServico.AUTO_RESIZE_OFF);
        jtListarServico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//SÓ PERMITI SELECIONAR UM DADO POR VEZ
        conecta.desconectar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListarServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSairListarServico;
    private javax.swing.JButton btVoltarListarServico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtListarServico;
    private javax.swing.JLabel lbHoras;
    private javax.swing.JLabel lbMinutos;
    private javax.swing.JLabel lbSegundos;
    // End of variables declaration//GEN-END:variables
}
